[project]
name = "it-learns-maze"
version = "0.1.0"
description = "AI learns maze"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neat-python>=0.92",
    "pygame>=2.6.1",
    "pyright>=1.1.391",
]
