name: Deploy to itch.io
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Build Pygbag
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Copy only certain files and folders
        run: |
          mkdir it-learns-maze
          cp -r game it-learns-maze
          cp -r neat it-learns-maze
          cp -r assets it-learns-maze
          cp -r checkpoints it-learns-maze
          cp main.py it-learns-maze
          cp button.py it-learns-maze
          cp config.txt it-learns-maze
          cp best.pickle it-learns-maze
      - name: Install pygbag
        run: python -m pip install pygbag
      - name: Build Game
        run: python -m pygbag --archive it-learns-maze

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Uploud game
        run: ./butler push it-learns-maze/build/web.zip "scrythepvp/it-learns-maze:html"
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
